from playwright.sync_api import sync_playwright
B=__import__('os').environ.get('APP_URL','http://localhost:5173')
res=[]
def ok(n,c): res.append((n,bool(c))); print(('PASS ' if c else 'FAIL ')+n)
with sync_playwright() as p:
    b=p.chromium.launch(); pg=b.new_page(viewport={'width':1440,'height':900})
    logs=[]; pg.on('console',lambda m: logs.append((m.type,m.text)) if m.type in('error','warning') else None); pg.on('pageerror',lambda e:logs.append(('pageerror',str(e))))
    pg.goto(B); pg.wait_for_timeout(1200); pg.screenshot(path='/tmp/app/dash.png')
    ok('dashboard KPI', pg.locator('.kpi').count()==4)
    ok('charts render bars', pg.locator('.recharts-bar-rectangle').count()>=14)
    # leads modal
    pg.click('text=2 callbacks'); pg.wait_for_timeout(300); pg.screenshot(path='/tmp/app/leads.png')
    ok('modal open dialog', pg.locator('role=dialog[name="Leads"]').count()==1)
    ok('lead 1 Mukunda', 'Lead 1 of 5' in pg.inner_text('.dialog__head') and 'Mukunda' in pg.inner_text('.lm__body'))
    ok('prev disabled at first', pg.locator('[aria-label="Previous lead"]').is_disabled())
    pg.click('[aria-label="Next lead"]'); ok('next -> Kavitha', 'Kavitha' in pg.inner_text('.lm__body') and 'Lead 2 of 5' in pg.inner_text('.dialog__head'))
    for _ in range(3): pg.click('[aria-label="Next lead"]')
    ok('last lead Ritu & next disabled', 'Lead 5 of 5' in pg.inner_text('.dialog__head') and pg.locator('[aria-label="Next lead"]').is_disabled())
    pg.click('text=ICP FIT BREAKDOWN'); ok('collapse expands', 'Budget Fit' in pg.inner_text('.lm__body'))
    pg.click('text=WHERE WE PICKED UP SIGNALS'); ok('collapse closes', 'Quotation Demanded' not in pg.inner_text('.lm__body'))
    pg.keyboard.press('Escape'); ok('Escape closes', pg.locator('.dialog').count()==0)
    pg.click('text=1 outcome'); pg.mouse.click(5,450); pg.wait_for_timeout(200); ok('backdrop closes', pg.locator('.dialog').count()==0)
    # plan
    pg.click('nav >> text=Plan'); pg.wait_for_timeout(300)
    ok('plan calls route', '/plan/calls' in pg.url and 'Ritu S.' in pg.inner_text('.plan-list'))
    pg.screenshot(path='/tmp/app/calls.png')
    pg.click('text=Ritu S.'); ok('row expands', 'Call now' in pg.inner_text('.plan-list'))
    pg.click('[aria-label="Next page"]'); ok('page 2 data', 'Page 2 of 3' in pg.inner_text('.pager') and 'Kavitha' in pg.inner_text('.plan-list') and 'Ritu' not in pg.inner_text('.plan-list'))
    pg.click('[aria-label="Next page"]'); ok('page 3 data & next disabled', 'Priya Iyer' in pg.inner_text('.plan-list') and pg.locator('[aria-label="Next page"]').is_disabled())
    pg.click('[aria-label="Previous page"]'); pg.click('[aria-label="Previous page"]')
    pg.click('.plan-row >> nth=1'); pg.click('button:has-text("Full picture")'); ok('full picture modal at Mukunda (idx 2)', 'Lead 2 of 6' in pg.inner_text('.dialog__head')); pg.keyboard.press('Escape')
    pg.click('.plan-row >> nth=0'); pg.click('button:has-text("Call now")'); ok('call panel active', pg.locator('.call-panel').count()==1); pg.wait_for_timeout(1200); ok('timer ticks', '00:0' in pg.inner_text('.call-panel') and '00:00' not in pg.inner_text('.call-panel'))
    pg.click('text=End call'); ok('call ended toast', 'ended' in pg.inner_text('.toasts'))
    pg.click('.subnav >> text=Incoming'); pg.wait_for_timeout(200); pg.screenshot(path='/tmp/app/incoming.png')
    ok('incoming total ₹81,860', '₹81,860' in pg.inner_text('.missed-summary') and pg.locator('text=Call back').count()>=5)
    pg.click('[aria-label="Call back Faizan A."]'); ok('callback starts call', 'Faizan' in pg.inner_text('.call-panel') and pg.locator('[aria-label="Called back Faizan A."]').is_disabled())
    pg.click('text=End call')
    pg.click('.subnav >> text=Recent'); pg.wait_for_timeout(200); pg.screenshot(path='/tmp/app/recent.png')
    pg.click('[aria-label="Review call with Mukunda R."]'); ok('recent detail', '4m 12s' in pg.inner_text('.dialog') and 'SOP' in pg.inner_text('.dialog')); pg.keyboard.press('Escape')
    pg.click('.subnav >> text=Practise a call'); ok('practice ringing', 'Incoming' in pg.inner_text('.call-panel')); pg.click('text=Accept'); pg.wait_for_timeout(1100); ok('practice active', '00:01' in pg.inner_text('.call-panel') or '00:02' in pg.inner_text('.call-panel')); pg.click('text=End call')
    # calendar
    pg.click('nav >> text=Calendar'); pg.wait_for_timeout(300); pg.screenshot(path='/tmp/app/cal.png')
    ok('Oct 2026 shown', 'October 2026' in pg.inner_text('.cal__nav'))
    ok('Oct 1 under Thursday (5th cell)', pg.locator('.cal__grid > *').nth(7+4).inner_text().strip().startswith('1'))
    ok('event dots 3', pg.locator('.cal__dot').count()==3)
    pg.click('[aria-label^="Friday, October 23"]'); ok('select date shows event', 'SOP coaching' in pg.inner_text('[aria-label="Selected day"]'))
    pg.click('[aria-label^="Saturday, October 24"]'); ok('empty day state', 'Nothing scheduled' in pg.inner_text('[aria-label="Selected day"]'))
    for _ in range(2): pg.click('[aria-label="Next month"]')
    ok('Dec 2026', 'December 2026' in pg.inner_text('.cal__nav'))
    pg.click('[aria-label="Next month"]'); ok('Dec->Jan 2027', 'January 2027' in pg.inner_text('.cal__nav'))
    pg.click('[aria-label="Previous month"]'); ok('Jan->Dec 2026', 'December 2026' in pg.inner_text('.cal__nav'))
    pg.click('.cal__today'); ok('Today resets', __import__('datetime').date.today().strftime('%B %Y') in pg.inner_text('.cal__nav') and pg.locator('.cal__day.is-selected').inner_text().strip()==str(__import__('datetime').date.today().day))
    # pulse
    pg.click('nav >> text=Pulse'); pg.wait_for_timeout(300); pg.screenshot(path='/tmp/app/pulse.png',full_page=False)
    ok('pulse home', 'AvaniBot' in pg.inner_text('.pulse') and 'cross-sell-agent' in pg.inner_text('.pulse'))
    pg.fill('[aria-label="Search Pulse"]','shipment'); ok('search filters', 'manage-shipment' in pg.inner_text('.pulse') and 'all-stores' not in pg.inner_text('.pulse')); pg.fill('[aria-label="Search Pulse"]','')
    pg.click('text=Kudos >> nth=0'); ok('kudos modal', pg.locator('.dialog').count()==1); pg.keyboard.press('Escape')
    pg.click('.row:has-text("callcentre-team")'); pg.wait_for_timeout(300); pg.screenshot(path='/tmp/app/channel.png')
    ok('channel route', '/pulse/callcentre-team' in pg.url and 'Confirm the 4:30pm callback' in pg.inner_text('.chan'))
    pg.click('[aria-label="Send message"]'); ok('empty validation', 'Type a message' in pg.inner_text('.chan__composer'))
    n=pg.locator('.msg').count(); pg.fill('[aria-label^="Message #"]','Hello team'); pg.keyboard.press('Enter'); pg.wait_for_timeout(200)
    ok('message appended & input cleared', pg.locator('.msg').count()==n+1 and pg.input_value('[aria-label^="Message #"]')=='' and pg.locator('.msg--mine').last.inner_text().find('Hello team')>=0)
    pg.click('text=Reschedule'); ok('reschedule options', pg.locator('text=6:00pm').count()==1); pg.click('text=6:00pm'); ok('pinned answered', 'Answered' in pg.inner_text('.needs--done') and 'reschedule' in pg.locator('.msg--mine').last.inner_text())
    pg.click('[aria-label="Back to Pulse"]'); ok('back nav', pg.url.endswith('/pulse'))
    pg.click('button:has-text("Daily Brief")'); ok('daily brief channel', 'Daily brief' in pg.inner_text('.chan__messages'))
    pg.goto(B+'/pulse/callcentre-team')  # reload resets in-memory state, so the pinned card is open again
    pg.click('button:has-text("Confirmed")'); ok('confirmed answer', 'Answered' in pg.inner_text('.needs--done'))
    pg.screenshot(path='/tmp/app/channel2.png')
    # mobile
    m=b.new_page(viewport={'width':390,'height':844}); m.on('pageerror',lambda e:logs.append(('pageerror',str(e))))
    for path in ['/','/plan/calls','/plan/incoming','/plan/recent','/calendar','/pulse','/pulse/callcentre-team']:
        m.goto(B+path); m.wait_for_timeout(500)
        ov=m.evaluate("document.documentElement.scrollWidth>window.innerWidth+1 || document.querySelector('.page').scrollWidth>document.querySelector('.page').clientWidth+1")
        ok('mobile no h-overflow '+path, not ov)
    m.goto(B); m.screenshot(path='/tmp/app/m_dash.png'); m.click('[aria-label="Toggle navigation"]'); m.wait_for_timeout(300); m.screenshot(path='/tmp/app/m_nav.png')
    m.click('nav >> text=Calendar'); ok('mobile nav navigates & closes', '/calendar' in m.url)
    m.goto(B+'/pulse/callcentre-team'); m.screenshot(path='/tmp/app/m_chan.png')
    print('CONSOLE:',[l for l in logs][:10])
    print('FAILS:',[n for n,c in res if not c])
    b.close()
